#!/usr/bin/expect -f

source [file join [file dirname $argv0] libtest.tcl]

set timeout 300
set env(TERM) xterm-256color
set env(SHELL) /bin/bash
set env(HOME) /home/gitlab-runner
set env(PATH) /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
set env(LOGNAME) gitlab-runner
set env(SHLVL) 2
set env(MAIL) /var/mail/gitlab-runner
set env(SUDO_UID) 1000
set env(SUDO_GID) 1000
set env(SUDO_COMMAND) /bin/bash

spawn sudo bash -c "sudo screen -S hikey -L -Logfile exec_log /dev/ttyXRUSB0 115200 | ./scripts/format_output.py"

# wait to boot hikey
if {[catch boot_hikey errmsg]} {
    puts $errmsg
    exit -1
}
sleep 5

# Test lwip network
# Boot lwip tcp server
exec sudo screen -x -S hikey -p 0 -X stuff "test_net_server.bin\n"
sleep 1
expect {
        "LWIP tcp server up!" {
        }
        timeout {
                spawn sudo screen -S hikey -X quit
                sleep 1
                exit -1
        }
}

exec sudo screen -x -S hikey -p 0 -X stuff  "test_net_client.bin 16\n"
sleep 1
expect {
        "LWIP network test finished!" {
        # success
        }
        timeout {
                spawn sudo screen -S hikey -X quit
                sleep 1
                exit -1
        }
}

# Test basic ipc
exec sudo screen -x -S hikey -p 0 -X stuff "client.bin\n"
sleep 1
expect {
        "exit now." {
                # success 
        }
        timeout {
                exit -1
        }
}

# Test sched
exec sudo screen -x -S hikey -p 0 -X stuff "test_sched.bin\n"
sleep 1
expect {
        "test_sched done" {
        }
        timeout {
                exit -1
        }
}

# Test sched
exec sudo screen -x -S hikey -p 0 -X stuff "test_fpu.bin\n"
sleep 1
expect {
        "test_fpu done" {
        }
        timeout {
                exit -1
        }
}

# Poll-related tests
exec sudo screen -x -S hikey -p 0 -X stuff "epoll_server.bin\n"
sleep 1
expect {
        "LWIP epoll server up" {
                # Boot lwip tcp client
                exec sudo screen -x -S hikey -p 0 -X stuff "poll_client.bin\n"
                sleep 1
                expect {
                        "LWIP epoll server done" {
                                # success
                        }
                        timeout {
                                exit -1
                        }
                }
        }
        timeout {
                exit -1
        }
}

exec sudo screen -x -S hikey -p 0 -X stuff "poll_server.bin\n"
sleep 1
expect {
        "LWIP poll server up" {
                # Boot lwip poll client
                exec sudo screen -x -S hikey -p 0 -X stuff "poll_client.bin\n"
                sleep 1
                expect {
                        "LWIP poll server done" {
                                # success
                        }
                        timeout {
                                exit -1
                        }
                }
        }
        timeout {
                exit -1
        }
}

# Notfication-related synchronizations:
# notification, semaphore, pthread_cond
exec sudo screen -x -S hikey -p 0 -X stuff "test_notifc.bin\n"
sleep 1
expect {
        "notifc test success" {
                # success
        }
        timeout {
                exit -1
        }
}

expect {
        "sem test success" {
                # success
        }
        timeout {
                exit -1
        }
}

expect {
        "cond test success" {
                # success
        }
        timeout {
                exit -1
        }
}

# Pthread tests:
exec sudo screen -x -S hikey -p 0 -X stuff "test_pthread.bin\n"
sleep 1
expect {
        "Pthread test finished!" {
                # success
        }
        timeout {
                exit -1
        }
}

exec sudo screen -x -S hikey -p 0 -X stuff "test_fs.bin\n"
sleep 1
expect {
        "FS test finished!" {
                # success
        }
        timeout {
                exit -1
        }
}

exec sudo screen -x -S hikey -p 0 -X stuff "test_eventfd.bin\n"
sleep 1
expect {
        "Finish eventfd test!" {
                # success
        }
        timeout {
                exit -1
        }
}

exec sudo screen -x -S hikey -p 0 -X stuff "timerfd.bin\n"
sleep 1
expect {
       "timerfd finished" {
                # success
        }
        timeout {
                exit -1
        }
}

exec sudo screen -x -S hikey -p 0 -X stuff "test_sleep.bin\n"
sleep 1
expect {
        "timeout notification complete" {
                # success
        }
        timeout {
                exit -1
        }
}

expect {
        "nanosleep complete" {
                # success
        }
        timeout {
                exit -1
        }
}

spawn sudo screen -S hikey -X quit
sleep 1

puts "Test OK."
